---
apiVersion: v1
kind: Secret
metadata:
  name: dhparam
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  dhparam.pem: LS0tLS1CRUdJTiBESCBQQVJBTUVURVJTLS0tLS0KTUlJQ0NBS0NBZ0VBblpHNkk4MnJ2T0diTnZNR1lWQmlzeEFmOVE1N2JYeTZTeHEvVWFkUExoczJTdW9PV0hCZAp4dmlUTVRUd21SUUdFUDV3K0lpb3FsZVFzSzZsRGpYK3cwZ1V4ZEkxVFMwdjljOC9Xd1lBMzJvM1JMSmJxOGJvCm42eFdOSXgxR2tVcEEwNkRnNHVvWE9HakorWWQvRGpZSGlwYnkwZmc0bEZrZURNaFZXTVp4eFNlM0hBY2VuakEKSVVScGtPM3ZHQ2tENlFOaDhtU0NZcUlKeVZSaWxscnVKNkpHajZWc0lkZWNXd3FwclFpeU1HSWNrNU9oWXJ0SQpKV0tVWUlpUVNqQ0wrYTZkUDZESjFzWmczUVMyZnlTamFJa3VEc2tCd01zNlJYWW41MWtXWUV5Wm1BTW51SmRmClg2QlpKLzJhcXVCQ0ZnWXYrdkVlWFVJUjNITmlyNVVaN0RIZVJVTlc5TjJlUWRpTmM1dkJ1eGxaOFExZWFKeWMKckcyTDNBK3dwK1NUclNQS1BvcGVCZCtucjdqRUlYejNENXNTMFdsRElGRk5ubno2bzFUWEt4SzU2bkpYVTl1UApiRTNCQnNxRnA5ellId3M4bWI2YUF4d0MrWEtvSXlrRVd1enNLaCt6cVluWWRuL3FDNlR5K2lzVnZ4UTU0WjZJCjZXbHFHMkpucnUyYjZqU0FZSURLdVdQMjR5UlE5MW9qdmU3emtkMmNicERuUzFmL1M5MUhTdlYrYVNKUyswUFcKeXdlUmJ5T3RIMmQzTkM2MTErYndBOGM1SDBhMXlLRTBkTUdtYVhnbWZ2WDZMQUNTUHRWNzBJL3RKeGY0RkYrbwpSUG1TYi9vVHRSSHBqcXFHOUdZNXZHQUlOUmoxeTh1bUFGUS9RNU5JOUMyTW1MbHIvUThGbDRzQ0FRST0KLS0tLS1FTkQgREggUEFSQU1FVEVSUy0tLS0tCg==
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  hsts-preload: 'true'
  server-snippet: |
    ssl_stapling on;
    ssl_stapling_verify on;
  server-tokens: 'false'
  ssl-ciphers: ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256
  ssl-dh-param: ingress-nginx/dhparam
  ssl-protocols: TLSv1.2 TLSv1.3
  ssl-session-cache-size: 15m
  ssl-session-tickets: 'false'
  ssl-session-timeout: 5m
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: udp-services
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
