---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: default
  labels:
    app.kubernetes.io/name: letsencrypt-issuer
    app.kubernetes.io/part-of: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: progamesigner+rfgames@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    http01: {}
