---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: v1-api-contact
  namespace: default
  labels:
    app.kubernetes.io/name: v1-api-contact
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: v1-api-contact
  template:
    metadata:
      labels:
        app.kubernetes.io/name: v1-api-contact
    spec:
      containers:
      - name: rfgames-contact-api-server
        image: progamesigner/rfgames-contact-api-server:1.3
        env:
        - name: CONTACT_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              key: CONTACT_DISCORD_WEBHOOK
              name: cluster-configs
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: http
        readinessProbe:
          tcpSocket:
            port: http
        resources:
          limits:
            cpu: 30m
            memory: 32Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
