---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: v1-api-contact
  name: v1-api-contact
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: v1-api-contact
  template:
    metadata:
      labels:
        app.kubernetes.io/name: v1-api-contact
    spec:
      automountServiceAccountToken: false
      containers:
      - name: rfgames-contact-api-server
        image: progamesigner/rfgames-contact-api-server:latest
        env:
        - name: CONTACT_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              key: CONTACT_DISCORD_WEBHOOK
              name: cluster-configs
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: http
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 32Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      serviceAccountName: rfgames-services
