---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-backend
  namespace: default
  labels:
    app.kubernetes.io/name: default-backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: default-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: default-backend
    spec:
      automountServiceAccountToken: false
      containers:
      - name: default-backend
        image: progamesigner/rfgames-default-backend:latest
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        resources:
          limits:
            cpu: 10m
            memory: 32Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
