---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager-rfgames
  namespace: monitor
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: monitor
---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: rfgames
  namespace: monitor
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: monitor
spec:
  baseImage: quay.io/prometheus/alertmanager
  nodeSelector:
    kubernetes.io/os: linux
  replicas: 2
  resources:
    requests:
      memory: 100Mi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager-rfgames
  version: v0.18.0
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitor
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: monitor
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 9093
    protocol: TCP
    targetPort: web
  selector:
    alertmanager: rfgames
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: default
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: monitor
spec:
  type: ExternalName
  externalName: alertmanager.monitor.svc.cluster.local
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alertmanager
  namespace: monitor
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: monitor
spec:
  endpoints:
  - interval: 30s
    port: web
  selector:
    matchLabels:
      alertmanager: rfgames
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/part-of: monitor
