apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- env: .env.production
  namespace: default
  name: api-server-configs
resources:
- ./10-ingress-namespace.yaml
- ./11-ingress-config.yaml
- ./12-ingress-nginx.yaml
- ./13-ingress-default.yaml
- ./20-monitor-namespace.yaml
- ./21-monitor-crds.yaml
- ./22-monitor-config.yaml
- ./23-monitor-operator.yaml
- ./24-monitor-alertmanager.yaml
- ./25-monitor-prometheus.yaml
- ./29-monitor-ingress.yaml
- ./30-cert-namespace.yaml
- ./31-cert-crds.yaml
- ./32-cert-manager.yaml
- ./33-cert-issuer.yaml
- ./90-v0-api-dps.yaml
- ./99-certificates.yaml
