apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: k8s.gcr.io/kube-state-metrics/kube-state-metrics
  newTag: v2.1.0
resources:
- ./rbac.yaml
- ./deployments.yaml
- ./services.yaml
