---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: default-backend
    app.kubernetes.io/part-of: default-backend
  name: default-backend
  namespace: default
spec:
  ingressClassName: ingress-nginx
  rules:
  - host: ''
    http:
      paths:
      - backend:
          service:
            name: default-backend
            port:
              name: http
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-methods: GET,POST,OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
  labels:
    app.kubernetes.io/name: v0-api-backend
    app.kubernetes.io/part-of: v0-api-backend
  name: v0-api-backend
  namespace: default
spec:
  ingressClassName: ingress-nginx
  rules:
  - host: dps.rfgames.tw
    http:
      paths:
      - backend:
          service:
            name: v0-api-dps
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - dps.rfgames.tw
    secretName: tls-tw-rfgames-dps
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-methods: GET,POST,OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: https://rfgames.tw
    nginx.ingress.kubernetes.io/enable-cors: 'true'
  labels:
    app.kubernetes.io/name: v1-api-backend
    app.kubernetes.io/part-of: v1-api-backend
  name: v1-api-backend
  namespace: default
spec:
  ingressClassName: ingress-nginx
  rules:
  - host: api.rfgames.tw
    http:
      paths:
      - backend:
          service:
            name: v1-api-apply
            port:
              name: http
        path: /v1/apply
        pathType: Prefix
      - backend:
          service:
            name: v1-api-contact
            port:
              name: http
        path: /v1/contact
        pathType: Prefix
  tls:
  - hosts:
    - api.rfgames.tw
    secretName: tls-tw-rfgames-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/temporal-redirect: https://discord.gg/xsSWwn3
  labels:
    app.kubernetes.io/name: v1-discord-backend
    app.kubernetes.io/part-of: v1-discord-backend
  name: v1-discord-backend
  namespace: default
spec:
  ingressClassName: ingress-nginx
  rules:
  - host: discord.rfgames.tw
  tls:
  - hosts:
    - discord.rfgames.tw
    secretName: tls-tw-rfgames-discord
