apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./default-backend.yaml
- ./v0-api-dps.yaml
- ./v1-api-apply.yaml
- ./v1-api-contact.yaml
- ./ingresses.yaml
- ./certificates.yaml
secretGenerator:
- env: .env.production
  namespace: default
  name: cluster-configs
