---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: v1-api-apply
  namespace: default
  labels:
    app.kubernetes.io/name: v1-api-apply
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: v1-api-apply
  template:
    metadata:
      labels:
        app.kubernetes.io/name: v1-api-apply
    spec:
      containers:
      - name: rfgames-apply-api-server
        image: progamesigner/rfgames-apply-api-server:1.3.1
        env:
        - name: APPLY_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              key: APPLY_DISCORD_WEBHOOK
              name: cluster-configs
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: http
        readinessProbe:
          tcpSocket:
            port: http
        resources:
          limits:
            cpu: 30m
            memory: 32Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
