---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: v1-api-apply
  name: v1-api-apply
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app.kubernetes.io/name: v1-api-apply
  type: ClusterIP
