---
apiVersion: v1
kind: Service
metadata:
  name: v1-api-apply
  labels:
    app.kubernetes.io/name: v1-api-apply
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: v1-api-apply
