---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: v0-api-dps
  name: v0-api-dps
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: v0-api-dps
  template:
    metadata:
      labels:
        app.kubernetes.io/name: v0-api-dps
    spec:
      automountServiceAccountToken: false
      containers:
      - name: gw2-dps-report
        image: progamesigner/gw2-dps-report:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: http
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 32Mi
      serviceAccountName: rfgames-services
