---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: v0-api-dps
  name: v0-api-dps
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app.kubernetes.io/name: v0-api-dps
  type: ClusterIP
