apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
  newTag: 0.30.0
resources:
- ./namespace.yaml
- ./rbac.yaml
- ./configs.yaml
- ./daemonsets.yaml
- ./services.yaml
