apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: k8s.gcr.io/ingress-nginx/controller
  newTag: v1.1.1
resources:
- ./configs.yaml
- ./daemonsets.yaml
- ./ingressclasses.yaml
- ./namespace.yaml
- ./rbac.yaml
- ./services.yaml
